### PR TITLE
Switch CI from travis-ci to GitHub actions

### PR DESCRIPTION
**Pull request by andrew**
Also testing against a range of currently supported ruby versions, plus 2.7 for backwards compatibility.

### CODE REVIEW

**Comment by aquasync** [comment]
Hi @andrew, I don't have much familiarity with github actions (or travis ci for that matter!) - I didn't add the initial continuous integration, that was @taichi-ishitani. What's the point of this switch - is it just that github ci is more integrated/easier to use?

**Comment by taichi-ishitani** [comment]
I switched my CI flow from travis to GitHub Actions 4 years ago because travis was very slow at that time.

**Comment by taichi-ishitani** [comment]
How about using the `bundler-cache: true` option of the `setup ruby` action like this?
https://github.com/taichi-ishitani/rupkl/blob/177f38d94116ef9b263c93fdf7eed717fba7d898/.github/workflows/ci.yml#L30

Then depdended gems will be installed automatically and so we can remove following 2 actions.
https://github.com/aquasync/ruby-ole/blob/322923b57cf3b92cdbe3a4054608160bc7ec6bc2/.github/workflows/ci.yml#L32-L36

**Comment by andrew** [comment]
I’m on holiday this week, can add it when I get back or feel free to edit the branch yourself, I think I made it writable to admins

**Comment by andrew** [comment]
@taichi-ishitani I've updated ci.yml now to use `bundler-cache: true`, I also added a Gemfile so that bundler correctly installs all the test dependencies.

@aquasync travis ci's free option for open source has got significantly worse over the past few years, github actions is nicely integrated into the standard github workflow, it's also fast, free and unrestrictred for open source projects.

I also noticed a few deprecation warnings in the logs but I'll open seperate PRs for those once this is merged.

**Comment by aquasync** [comment]
Ok thanks @andrew.

**Comment by aquasync** [comment]
It doesn't seem to be running; looking at the config, is the issue that it mentions push/pr to "main" branch, whereas this repo has "master"?

**Comment by andrew** [comment]
> It doesn't seem to be running; looking at the config, is the issue that it mentions push/pr to "main" branch, whereas this repo has "master"?

yep, sorry my mistake, updated here: https://github.com/aquasync/ruby-ole/pull/30

**Comment by aquasync** [comment]
Cool, yep that fixed it - thanks!

**Pull request merged**
